name: Ping Supabase to Prevent Pausing

permissions:
    contents: read

on:
    schedule:
        - cron: '0 9 * * 1,2,3,4,5' # Runs at 9:00 AM every Monday and Thursday

jobs:
    ping:
        environment: Supabase
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '16'

            - name: Install dependencies
              run: npm install @supabase/supabase-js

            - name: Ping Supabase
              env:
                  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
                  SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
              run: |
                  node -e "
                  const { createClient } = require('@supabase/supabase-js');
                  const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY);
                  supabase.from('bootcamp').select('id').limit(2).then(data=>console.log(data)).catch(err=>console.log(err.message));
                  "
